server:
  port: 80
spring:
  application:
    name: cis
  thymeleaf:
    mode: HTML5
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.101:3306/cis?characterEncoding=utf-8
    username: yuyongtao
    password: yuyongtao
mybatis:
  typeAliasesPackage: com.oa.cis.entity
  mapperLocations: classpath:mapper/*.xml
logging:
  file: cis.log